spring.application.name=campusfieldtrack-backend
server.port=8080
server.servlet.context-path=/api

spring.datasource.url=jdbc:mysql://localhost:3306/CampusTrack?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=PremSai
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.jdbc.fetch_size=50
spring.jpa.show-sql=false

spring.jackson.serialization.write-dates-as-timestamps=false

jwt.secret=YW91cHNlY3JldGp3dGtleWNoYW5nZXRoaXNpbnByb2R1Y3Rpb25hdGxlYXN0MzJjaGFyYWN0ZXJzbG9uZ2FuZGV2ZW5sb25nZXI=
jwt.expiration=86400000

logging.level.root=INFO
logging.level.com.campusfieldtrack=DEBUG
